---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order
  labels:
    app: Order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Order
  template:
    metadata:
      labels:
        app: Order
    spec:
      containers:
        - name: Order
          image: username/Order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: OrderManagement
  labels:
    app: OrderManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderManagement
  template:
    metadata:
      labels:
        app: OrderManagement
    spec:
      containers:
        - name: OrderManagement
          image: username/OrderManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery
  template:
    metadata:
      labels:
        app: Delivery
    spec:
      containers:
        - name: Delivery
          image: username/Delivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MessageManagement
  labels:
    app: MessageManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MessageManagement
  template:
    metadata:
      labels:
        app: MessageManagement
    spec:
      containers:
        - name: MessageManagement
          image: username/MessageManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Pay
  template:
    metadata:
      labels:
        app: Pay
    spec:
      containers:
        - name: Pay
          image: username/Pay:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Order
  labels:
    app: Order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Order


---


apiVersion: v1
kind: Service
metadata:
  name: OrderManagement
  labels:
    app: OrderManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: OrderManagement


---


apiVersion: v1
kind: Service
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Delivery


---


apiVersion: v1
kind: Service
metadata:
  name: MessageManagement
  labels:
    app: MessageManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MessageManagement


---


apiVersion: v1
kind: Service
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Pay

